- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      cloud.google.com/neg: '{"ingress":true}'
    creationTimestamp: "2023-02-15T21:41:08Z"
    finalizers:
    - service.kubernetes.io/load-balancer-cleanup
    labels:
      app: hello-app
    name: hello-app-service
    namespace: default
    resourceVersion: "978692"
    uid: ea29d253-ebe2-4e1e-a438-7497faf20f33
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.77.3.50
    clusterIPs:
    - 10.77.3.50
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 31345
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: hello-app
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 34.138.232.126
